# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-01-25 15:32
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_auto_20180123_2133'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ad',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='Modificado em')),
            ],
            options={
                'verbose_name': 'Anúncio',
                'verbose_name_plural': 'Anúncios',
            },
        ),
        migrations.AlterModelOptions(
            name='supermarket',
            options={'ordering': ['name'], 'verbose_name': 'Super Mercado', 'verbose_name_plural': 'Super Mercados'},
        ),
        migrations.RemoveField(
            model_name='product',
            name='superMarket',
        ),
        migrations.AddField(
            model_name='ad',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.Product', verbose_name='Produto'),
        ),
        migrations.AddField(
            model_name='ad',
            name='superMarket',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.SuperMarket', verbose_name='Super Mercado'),
        ),
    ]
