# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-01-27 23:47
from __future__ import unicode_literals

from decimal import Decimal
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        ('catalog', '0004_auto_20180125_1338'),
    ]

    operations = [
        migrations.AddField(
            model_name='ad',
            name='quantity',
            field=models.IntegerField(default=1, verbose_name='Quantidade'),
        ),
        migrations.AddField(
            model_name='product',
            name='size',
            field=models.FloatField(default=None, verbose_name='Tamanho'),
        ),
        migrations.AddField(
            model_name='product',
            name='unit',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='core.Unit', verbose_name='Unidade'),
        ),
        migrations.AlterField(
            model_name='ad',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=8, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Preço'),
        ),
        migrations.AlterField(
            model_name='product',
            name='barcode',
            field=models.BigIntegerField(default=None, verbose_name='Código de barras'),
        ),
    ]
