# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-01-28 00:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0006_auto_20180127_2147'),
    ]

    operations = [
        migrations.AddField(
            model_name='ad',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='catalog/ad/images', verbose_name='Imagem'),
        ),
    ]
